### PR TITLE
Jellyfin Integration Guide

### PR DESCRIPTION
**Pull request by donkevlar**
Wrote up a simple jellyfin guide as it wasn't well defined in their SSO Plugin page. Let me know if you need other documentation! I've been using it with other applications and Im happy to help!

### CODE REVIEW

**Comment by stonith404** [comment]
Great, thank you :)  Could you please run a language check tool like ChatGPT on the jellyfin.md file? I noticed a few typos and grammar mistakes.

**Comment by donkevlar** [comment]
Done 👍

**Comment by stonith404** [comment]
Thanks :) Sorry one more thing, please replace "Pocket-ID" with "Pocket ID" as the correct name is without an hyphen.

**Comment by donkevlar** [comment]
Updated the file. Thanks,

**Comment by stonith404** [comment]
Thank you again!

**Pull request merged**
